### ISSUE TITLE
bad format

### ISSUE THREAD

**Issue by LNeway** [dlubarov/gifencoder#1]
Hello,

I try to use the code to create gif file on Android phone, but it seems that the format is incorrect.

that is my code.

```java
File gifFile = new File(file + "test.gif");
gifFile.createNewFile();

FileOutputStream outputStream = new FileOutputStream(gifFile);

GifEncoder encoder = new GifEncoder(outputStream, 120, 90, 0);
ImageOptions options = new ImageOptions();
options.setDelay(100, TimeUnit.MILLISECONDS);

Bitmap bitmap = Bitmap.createBitmap(120, 90, Bitmap.Config.ARGB_8888);

int pixls [] = new int [120 * 90];

bitmap.getPixels(pixls, 0, 120, 0, 0, 120, 90);

for (int i = 1; i <= 9; ++i) {
    encoder.addImage(pixls, 120, options);
}
encoder.finishEncoding();
outputStream.close();
Log.e("GIF", "create gif ok");
```

there is no content in the bitmap, but the file created should be recognized. right ?

Thanks for your help...

**Comment by dlubarov** [comment]
Hey, thanks for trying the library! I don't understand what you mean about the format being incorrect -- is there a runtime error, or the code runs okay but generates an invalid gif file? If it's an invalid gif file, please attach it.

**Comment by LNeway** [comment]
Thanks for your reply

That is the [gif](https://github.com/LNeway/gifencoder/blob/master/test.gif) file created by the code.

**Comment by dlubarov** [comment]
Thanks for reporting this. It was a bug affecting images with a single (unique) color. My code was attempting to write a color table of size 1, which isn't possible, since the color table size is encoded as `2^(n+1)` for some (unsigned) n.

Should be fixed now; please try the latest code.

**Comment by LNeway** [comment]
Great job!!!

Thanks for your help ~
